title: PNews 
description: "Built with Jekyll"
author: platsaver

# Basic Site Info
title: PNews
description: "Built with Jekyll"
author: platsaver

# Site Flag
flag:
  show: true
  path: /newtech1/assets/57c2d4726267e16dbad01549dac68326.png

# Comments
disqus:
  enabled: true
  shortname: quan

# Analytics
google_analytics: G-GRV8PX7ZN1

# Ads
adsense:
  enabled: true
  data-ad-client: ca-pub-9280169319319657  #REPLACEME

# Collections
collections:
  posts:
    output: true                                                                                                                                                                                                                                          
    permalink: /:categories/:year/:month/:day/:title/
  staff:
    output: true
    permalink: /about/staff/:title

# Build settings
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

baseurl: '/newtech1'  # Subdirectory where the site lives

github: 
  username: platsaver

jekyll_admin:
  homepage: "posts"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      title: ""
      subhed: ""
      author: ""
      author-title: ""
      featured-image:
        path: ""
        cutline: ""
        credit: ""
      category: ""
      keywords: []

collections:
  subcategories:
    output: true
    permalink: /:collection/:name/